### PR TITLE
Refactor out a service so that URL generation can be used in code

### PR DESCRIPTION
**Pull request by jakehockey10**
Hello,

Thanks for this super simple and effective library for integrating Gravatar into Angular apps.  I wanted to be able to use this library, but in code and not just in a template as a directive.  Is there any chance I could get some help making this work?

I've attempted to use my fork in an angular app, but when I include the `GravatarModule` in my imports, and inject my new `GravatarService` into a component, Angular fails to resolve that service.

Do you know what I would need to do to fix this pull request so that one can either use the directive in their templates or the service in their code?

Thanks for any and all feedback/help!

### CODE REVIEW

**Review by gopumon — COMMENTED** [review]
Tested the code. Working fine.

**Comment by gopumon** [comment]
Updated the NPM repository with your feature. (v 1.2.0)

**Comment by gopumon** [comment]
There was a small issue with the service while using with dynamic email variable. Had to remove the check for email in url function.

**Comment by jakehockey10** [comment]
Did you test this with a new app? Could I see how you got it working? I still can't get my app to resolve the service after importing the `GravatarModule`

**Comment by gopumon** [comment]
Try compiling the code using `tsc`.

**Comment by gopumon** [comment]
Try version 1.2.1 from npm. It is same as master branch as of now.

**Pull request merged**
